class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'fr': {
      'app_name': 'ChantierPro',
      'app_subtitle': 'Gestion de chantiers professionnelle',
      'login': 'Connexion',
      'login_subtitle': 'Connectez-vous à votre espace chantier',
      'register': 'Inscription',
      'register_subtitle': 'Créez votre compte professionnel',
      'email': 'Adresse e-mail',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'first_name': 'Prénom',
      'last_name': 'Nom',
      'phone': 'Téléphone',
      'role': 'Rôle',
      'remember_me': 'Se souvenir de moi',
      'forgot_password': 'Mot de passe oublié?',
      'no_account': 'Pas encore de compte?',
      'have_account': 'Déjà un compte?',
      'sign_up': 'S\'inscrire',
      'sign_in': 'Se connecter',
      'dashboard': 'Tableau de bord',
      'chantiers': 'Chantiers',
      'tasks': 'Tâches',
      'reports': 'Rapports',
      'profile': 'Profil',
      'total_chantiers': 'Chantiers',
      'total_tasks': 'Tâches',
      'total_budget': 'Budget Total',
      'total_reports': 'Rapports',
      'add_chantier': 'Ajouter un chantier',
      'chantier_name': 'Nom du chantier',
      'client': 'Client',
      'description': 'Description',
      'address': 'Adresse',
      'budget': 'Budget',
      'start_date': 'Date de début',
      'end_date': 'Date de fin',
      'status': 'Statut',
      'en_cours': 'En cours',
      'planifie': 'Planifié',
      'termine': 'Terminé',
      'retard': 'Retard',
      'en_attente': 'En attente',
      'suspendu': 'Suspendu',
      'attention': 'Attention',
      'all': 'Tous',
      'search': 'Rechercher...',
      'add_task': 'Ajouter une tâche',
      'new_task': 'Nouvelle tâche',
      'title': 'Titre',
      'task_title': 'Titre de la tâche',
      'deadline': 'Date limite',
      'employee': 'Employé',
      'add_report': 'Ajouter un rapport',
      'new_report': 'Nouveau rapport',
      'report_date': 'Date du rapport',
      'report_type': 'Type de rapport',
      'report_content': 'Contenu du rapport',
      'content': 'Contenu',
      'daily': 'Journalier',
      'monthly': 'Mensuel',
      'inspection': 'Inspection',
      'incident': 'Incident',
      'meeting': 'Réunion',
      'closure': 'Clôture',
      'chantier_details': 'Détails du chantier',
      'info': 'Informations',
      'progress': 'Avancement',
      'actions': 'Actions',
      'category': 'Catégorie',
      'priority': 'Priorité',
      'consumed': 'Consommé',
      'remaining': 'Restant',
      'logout': 'Déconnexion',
      'logout_confirm': 'Voulez-vous vous déconnecter?',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'save': 'Enregistrer',
      'dark_mode': 'Mode sombre',
      'language': 'Langue',
      'settings': 'Paramètres',
      'personal_info': 'Informations personnelles',
      'my_stats': 'Mes statistiques',
      'notifications': 'Notifications',
      'good_morning': 'Bonjour',
      'recent_chantiers': 'Chantiers récents',
      'alerts': 'Alertes',
      'delay_alert': 'Retard détecté',
      'budget_alert': 'Dépassement budget',
      'view_all': 'Voir tout',
      'no_data': 'Aucune donnée',
      'loading': 'Chargement...',
      'error_required': 'Ce champ est requis',
      'error_email': 'Email invalide',
      'error_password_min': 'Minimum 6 caractères',
      'error_password_match': 'Les mots de passe ne correspondent pas',
      'chef_chantier': 'Chef de chantier',
      'conducteur_travaux': 'Conducteur de travaux',
      'ingenieur': 'Ingénieur',
      'technicien': 'Technicien',
      'ouvrier': 'Ouvrier',
      'admin': 'Administrateur',
      'good_afternoon': 'Bon après-midi',
      'good_evening': 'Bonsoir',
      'active_chantiers': 'Chantiers actifs',
      'late_tasks': 'Tâches en retard',
      'reports_this_month': 'Rapports ce mois',
      'in_total': 'au total',
      'of_tasks': 'sur {n} tâches',
      'consumed_pct': '{n}% consommé',
      'chart_title': 'Avancement des chantiers',
      'chart_subtitle': 'Basé sur les tâches',
      'no_chart_data': 'Aucune donnée à afficher',
      'retry': 'Réessayer',
      'new_chantier': 'Nouveau chantier',
      'projects_total': '{n} projets au total',
      'no_chantier_yet':
          'Aucun chantier pour le moment.\nCréez votre premier chantier !',
      'no_chantier_found': 'Aucun chantier trouvé',
      'no_result_for': 'Aucun résultat pour "{q}".\nEssayez un autre terme.',
      'no_status_match':
          'Aucun chantier avec ce statut.\nModifiez vos filtres.',
      'alert_delay_one': '1 chantier en retard nécessite votre attention',
      'alert_delay_many': '{n} chantiers en retard nécessitent votre attention',
      'create_chantier_first':
          'Créez d\'abord un chantier avant d\'ajouter cet élément.',
      'chantier_created': 'Chantier "{x}" créé avec succès',
      'task_created': 'Tâche créée avec succès',
      'report_created': 'Rapport créé avec succès',
      'photo_uploaded': 'Photo envoyée avec succès',
      'photos': 'Photos',
      'add_photo': 'Ajouter une photo',
      'gallery': 'Galerie',
      'camera': 'Caméra',
      'pick_from_gallery': 'Choisir depuis la galerie',
      'take_photo': 'Prendre une photo',
      'author': 'Auteur',
      'select_chantier': 'Chantier',
      'attach_photos': 'Joindre des photos',
      'error_generic': 'Une erreur est survenue. Veuillez réessayer.',
      'password_min8': 'Minimum 8 caractères',
      'create_first_report':
          'Créez d\'abord un rapport pour ce chantier afin d\'y joindre des photos.',
      'no_photos': 'Aucune photo pour ce chantier',
      'no_reports': 'Aucun rapport',
      'no_tasks': 'Aucune tâche',
      'my_chantiers': 'Chantiers',
      'my_tasks': 'Tâches',
      'my_reports': 'Rapports',
      'admin_dashboard': 'Tableau de bord Admin',
      'no_notifications': 'Aucune notification',
      'add_expense': 'Ajouter une dépense',
      'amount': 'Montant',
      'invalid_amount': 'Montant invalide',
      'expense_date': 'Date de la dépense',
      'budget_exceeded': 'Budget dépassé !',
      'currency': 'Devise',
      'multi_currency': 'Devises multiples',
      'from': 'Du',
      'filters': 'Filtres',
      'filter_period': 'Filtrer par période',
      'filter_by_day': 'Filtrer par date',
      'filter_address_hint': 'Ex: Nouakchott, Ksar...',
      'all_chantiers': 'Tous les chantiers',
      'select_date': 'Sélectionner une date',
      'date': 'Date',
      'apply': 'Appliquer',
      'reset': 'Réinitialiser',
      'to': 'Au',
      'delete_chantier_warning':
          'Supprimer le chantier "{x}" ? Ses tâches, rapports, photos et dépenses seront aussi supprimés. Action irréversible.',
      'delete_task_warning':
          'Supprimer cette tâche ? Cette action est irréversible.',
      'delete_report_warning':
          'Supprimer ce rapport (et ses photos) ? Cette action est irréversible.',
      'chantier_deleted': 'Chantier supprimé',
      'task_deleted': 'Tâche supprimée',
      'report_deleted': 'Rapport supprimé',
      'late_chantier': 'Chantier en retard',
      'late_task': 'Tâche en retard',
      'site_managers': 'Chefs de chantier',
      'users_total_suffix': 'utilisateurs',
      'delayed_suffix': 'en retard',
      'consumed_budget': 'Budget consommé',
      'of_budget': 'de',
      'all_chantiers_included': 'tous chantiers',
      'expenses': 'Dépenses',
      'management_modules': 'Modules de gestion',
      'manage_chefs': 'Gestion des chefs',
      'assignments': 'Affectations',
      'recent_alerts': 'Alertes récentes',
      'no_alerts': 'Aucune alerte',
      'no_expenses': 'Aucune dépense',
      'no_chefs': 'Aucun chef de chantier',
      'no_assignments': 'Aucune affectation',
      'add_chef': 'Nouveau chef',
      'edit_chef': 'Modifier le chef',
      'chef_created': 'Chef de chantier créé avec succès',
      'chef_updated': 'Chef de chantier modifié avec succès',
      'chef_deleted': 'Chef de chantier supprimé',
      'confirm_delete': 'Confirmer la suppression',
      'delete_chef_warning':
          'Supprimer le compte de "{x}" ? Cette action est irréversible.',
      'delete_assignment_warning':
          'Supprimer cette affectation ? Cette action est irréversible.',
      'delete': 'Supprimer',
      'invalid_email': 'Email invalide',
      'password_required_on_update':
          'Requis : le serveur exige un mot de passe à chaque modification.',
      'new_assignment': 'Nouvelle affectation',
      'assignment_created': 'Affectation créée avec succès',
      'assignment_deleted': 'Affectation supprimée',
      'duplicate_assignment': 'Ce chef est déjà affecté à ce chantier.',
      'assignment_date': 'Date d\'affectation',
      'need_chef_and_chantier':
          'Créez d\'abord au moins un chantier et un chef de chantier.',
      'back': 'Retour',
      'consultation': 'Consultation',
      'suspend_chantier': 'Suspendre',
      'resume_chantier': 'Reprendre',
      'suspended': 'Suspendu',
      'suspend_task': 'Suspendre la tâche',
      'resume_task': 'Reprendre la tâche',
      'tasks_in_delay': 'tâche(s) en retard',
      'start_task': 'Démarrer',
      'complete_task': 'Terminer',
      'responsible': 'Responsable',
      'actual_start': 'Début réel',
      'actual_end': 'Fin réelle',
      'delay_days': 'Retard',
      'history': 'Historique',
      'no_history': 'Aucune action enregistrée',
      'tasks_total': '{n} tâches au total',
      'tasks_stats': 'Tâches associées',
      'tasks_completed': 'Terminées',
      'tasks_in_progress': 'En cours',
      'tasks_planned': 'Planifiées',
      'tasks_delayed': 'En retard',
      'reports_total': '{n} rapports au total',
      'filter_chantiers': 'Filtrer les chantiers',
      'filter_tasks': 'Filtrer les tâches',
      'filter_reports': 'Filtrer les rapports',
      'period': 'Période',
      'date_start': 'Date de début',
      'date_end': 'Date de fin',
      // === NOUVELLES CLÉS ===
      'quick_add': 'Ajout rapide',
      'add': 'Ajouter',
      'quick_access': 'Accès rapide',
      'operations': 'Opérations',
    },
    'en': {
      'app_name': 'ChantierPro',
      'app_subtitle': 'Professional construction management',
      'login': 'Login',
      'login_subtitle': 'Sign in to your construction workspace',
      'register': 'Register',
      'register_subtitle': 'Create your professional account',
      'email': 'Email address',
      'password': 'Password',
      'confirm_password': 'Confirm password',
      'first_name': 'First name',
      'last_name': 'Last name',
      'phone': 'Phone',
      'role': 'Role',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot password?',
      'no_account': 'Don\'t have an account?',
      'have_account': 'Already have an account?',
      'sign_up': 'Sign up',
      'sign_in': 'Sign in',
      'dashboard': 'Dashboard',
      'chantiers': 'Sites',
      'tasks': 'Tasks',
      'reports': 'Reports',
      'profile': 'Profile',
      'total_chantiers': 'Sites',
      'total_tasks': 'Tasks',
      'total_budget': 'Total Budget',
      'total_reports': 'Reports',
      'add_chantier': 'Add a site',
      'chantier_name': 'Site name',
      'client': 'Client',
      'description': 'Description',
      'address': 'Address',
      'budget': 'Budget',
      'start_date': 'Start date',
      'end_date': 'End date',
      'status': 'Status',
      'en_cours': 'In progress',
      'planifie': 'Planned',
      'termine': 'Completed',
      'retard': 'Delayed',
      'en_attente': 'Pending',
      'suspendu': 'Suspended',
      'attention': 'Attention',
      'all': 'All',
      'search': 'Search...',
      'add_task': 'Add a task',
      'new_task': 'New task',
      'title': 'Title',
      'task_title': 'Task title',
      'deadline': 'Deadline',
      'employee': 'Employee',
      'add_report': 'Add a report',
      'new_report': 'New report',
      'report_date': 'Report date',
      'report_type': 'Report type',
      'report_content': 'Report content',
      'content': 'Content',
      'daily': 'Daily',
      'monthly': 'Monthly',
      'inspection': 'Inspection',
      'incident': 'Incident',
      'meeting': 'Meeting',
      'closure': 'Closure',
      'chantier_details': 'Site details',
      'info': 'Information',
      'progress': 'Progress',
      'actions': 'Actions',
      'category': 'Category',
      'priority': 'Priority',
      'consumed': 'Consumed',
      'remaining': 'Remaining',
      'logout': 'Logout',
      'logout_confirm': 'Do you want to logout?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'save': 'Save',
      'dark_mode': 'Dark mode',
      'language': 'Language',
      'settings': 'Settings',
      'personal_info': 'Personal information',
      'my_stats': 'My statistics',
      'notifications': 'Notifications',
      'good_morning': 'Good morning',
      'recent_chantiers': 'Recent sites',
      'alerts': 'Alerts',
      'delay_alert': 'Delay detected',
      'budget_alert': 'Budget overrun',
      'view_all': 'View all',
      'no_data': 'No data',
      'loading': 'Loading...',
      'error_required': 'This field is required',
      'error_email': 'Invalid email',
      'error_password_min': 'Minimum 6 characters',
      'error_password_match': 'Passwords do not match',
      'chef_chantier': 'Site manager',
      'conducteur_travaux': 'Works supervisor',
      'ingenieur': 'Engineer',
      'technicien': 'Technician',
      'ouvrier': 'Worker',
      'admin': 'Administrator',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'active_chantiers': 'Active sites',
      'late_tasks': 'Late tasks',
      'reports_this_month': 'Reports this month',
      'in_total': 'in total',
      'of_tasks': 'of {n} tasks',
      'consumed_pct': '{n}% consumed',
      'chart_title': 'Site progress',
      'chart_subtitle': 'Based on tasks',
      'no_chart_data': 'No data to display',
      'retry': 'Retry',
      'new_chantier': 'New site',
      'projects_total': '{n} projects in total',
      'no_chantier_yet': 'No sites yet.\nCreate your first site!',
      'no_chantier_found': 'No site found',
      'no_result_for': 'No result for "{q}".\nTry another term.',
      'no_status_match': 'No site with this status.\nChange your filters.',
      'alert_delay_one': '1 delayed site needs your attention',
      'alert_delay_many': '{n} delayed sites need your attention',
      'create_chantier_first': 'Create a site first before adding this item.',
      'chantier_created': 'Site "{x}" created successfully',
      'task_created': 'Task created successfully',
      'report_created': 'Report created successfully',
      'photo_uploaded': 'Photo uploaded successfully',
      'photos': 'Photos',
      'add_photo': 'Add a photo',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'pick_from_gallery': 'Pick from gallery',
      'take_photo': 'Take a photo',
      'author': 'Author',
      'select_chantier': 'Site',
      'attach_photos': 'Attach photos',
      'error_generic': 'An error occurred. Please try again.',
      'password_min8': 'Minimum 8 characters',
      'create_first_report':
          'Create a report for this site first in order to attach photos.',
      'no_photos': 'No photos for this site',
      'no_reports': 'No reports',
      'no_tasks': 'No tasks',
      'my_chantiers': 'Sites',
      'my_tasks': 'Tasks',
      'my_reports': 'Reports',
      'admin_dashboard': 'Admin Dashboard',
      'no_notifications': 'No notifications',
      'add_expense': 'Add expense',
      'amount': 'Amount',
      'invalid_amount': 'Invalid amount',
      'expense_date': 'Expense date',
      'budget_exceeded': 'Budget exceeded!',
      'currency': 'Currency',
      'multi_currency': 'Multiple currencies',
      'from': 'From',
      'filters': 'Filters',
      'filter_period': 'Filter by period',
      'filter_by_day': 'Filter by date',
      'filter_address_hint': 'Ex: Nouakchott, Ksar...',
      'all_chantiers': 'All sites',
      'select_date': 'Select a date',
      'date': 'Date',
      'apply': 'Apply',
      'reset': 'Reset',
      'to': 'To',
      'delete_chantier_warning':
          'Delete site "{x}"? Its tasks, reports, photos and expenses will also be deleted. This cannot be undone.',
      'delete_task_warning': 'Delete this task? This cannot be undone.',
      'delete_report_warning':
          'Delete this report (and its photos)? This cannot be undone.',
      'chantier_deleted': 'Site deleted',
      'task_deleted': 'Task deleted',
      'report_deleted': 'Report deleted',
      'late_chantier': 'Delayed site',
      'late_task': 'Late task',
      'site_managers': 'Site managers',
      'users_total_suffix': 'users',
      'delayed_suffix': 'delayed',
      'consumed_budget': 'Consumed budget',
      'of_budget': 'of',
      'all_chantiers_included': 'all sites',
      'expenses': 'Expenses',
      'management_modules': 'Management modules',
      'manage_chefs': 'Manage site managers',
      'assignments': 'Assignments',
      'recent_alerts': 'Recent alerts',
      'no_alerts': 'No alerts',
      'no_expenses': 'No expenses',
      'no_chefs': 'No site managers',
      'no_assignments': 'No assignments',
      'add_chef': 'New manager',
      'edit_chef': 'Edit manager',
      'chef_created': 'Site manager created successfully',
      'chef_updated': 'Site manager updated successfully',
      'chef_deleted': 'Site manager deleted',
      'confirm_delete': 'Confirm deletion',
      'delete_chef_warning':
          'Delete the account of "{x}"? This action cannot be undone.',
      'delete_assignment_warning':
          'Delete this assignment? This action cannot be undone.',
      'delete': 'Delete',
      'invalid_email': 'Invalid email',
      'password_required_on_update':
          'Required: the server expects a password on every update.',
      'new_assignment': 'New assignment',
      'assignment_created': 'Assignment created successfully',
      'assignment_deleted': 'Assignment deleted',
      'duplicate_assignment': 'This manager is already assigned to this site.',
      'assignment_date': 'Assignment date',
      'need_chef_and_chantier':
          'Create at least one site and one site manager first.',
      'back': 'Back',
      'consultation': 'Consultation',
      'suspend_chantier': 'Suspend',
      'resume_chantier': 'Resume',
      'suspended': 'Suspended',
      'suspend_task': 'Suspend task',
      'resume_task': 'Resume task',
      'tasks_in_delay': 'task(s) delayed',
      'start_task': 'Start',
      'complete_task': 'Complete',
      'responsible': 'Responsible',
      'actual_start': 'Actual start',
      'actual_end': 'Actual end',
      'delay_days': 'Delay',
      'history': 'History',
      'no_history': 'No actions recorded',
      'tasks_total': '{n} tasks total',
      'tasks_stats': 'Related tasks',
      'tasks_completed': 'Completed',
      'tasks_in_progress': 'In progress',
      'tasks_planned': 'Planned',
      'tasks_delayed': 'Delayed',
      'reports_total': '{n} reports total',
      'filter_chantiers': 'Filter sites',
      'filter_tasks': 'Filter tasks',
      'filter_reports': 'Filter reports',
      'period': 'Period',
      'date_start': 'Start date',
      'date_end': 'End date',
      // === NOUVELLES CLÉS ===
      'quick_add': 'Quick add',
      'add': 'Add',
      'quick_access': 'Quick access',
      'operations': 'Operations',
    },
  };

  static String get(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['fr']?[key] ?? key;
  }

  /// Récupère une chaîne et remplace les paramètres {n}, {x}, {q}...
  static String getP(String key, String lang, Map<String, String> params) {
    var s = get(key, lang);
    params.forEach((k, v) => s = s.replaceAll('{$k}', v));
    return s;
  }
}
